### PR TITLE
Improved Documentation

### PR DESCRIPTION
**Pull request by thesauravkarmakar**

### CODE REVIEW

**Comment by thesauravkarmakar** [comment]
Let me know about your Tech Stack, to add it to the section

**Comment by Git-Harshit** [comment]
Thank you for the Pull Request #6, I am merging it right away! 😄

**Comment by thesauravkarmakar** [comment]
> Thank you for the Pull Request #6, I am merging it right away! 😄

Sure! I have told my friend to look over your UI/UX.

**Comment by Git-Harshit** [comment]
> Sure! I have told my friend to look over your UI/UX.

Thanks a lot @thesauravkarmakar for the help! I really appreciate it. 😊

**Pull request merged**
